version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
    groups:
      go-dependencies:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "maintain"
      prefix-development: "maintain"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "ci"
      prefix-development: "ci"

  - package-ecosystem: "npm"
    directory: "/docs/user"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
    groups:
      docs-dependencies:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "docs"
      prefix-development: "docs"
